title: Nate Guevin - Bennington College
description: An online space for everything from Bennington College's Philosophy of Data and The Internet Made Real classes.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
