title: Nate Guevin - Philosophy of Data
description: An online space for everything from Bennington College's Philosophy of Data class.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
